### ISSUE TITLE
Always update major release tag 

### ISSUE THREAD

**Issue by felipecrs** [GabrielBB/xvfb-action#13]
Hi, awesome action. A suggestion:

Update the major release tag (git tag `v1`) when you release another version matching that major version, so users could use your action with `@v1` instead of `@v1.2`. It's one of the best practices for GitHub Actions. ;)

See: https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#recommendations

It's quite simple:

> ```sh-session
> $ git tag -fa v1 -m "Update v1 tag"
> $ git push origin v1 --force
> ```

**Comment by felipecrs** [comment]
@GabrielBB quite simple:

```sh-session
$ git tag -f v1
$ git push -f --tags
```

**Comment by GabrielBB** [comment]
@felipecrs Good stuff!! I tried it, all new commits are now in [release @v1](https://github.com/GabrielBB/xvfb-action/releases/tag/v1). Updated README to use major tag. Thanks
