### ISSUE TITLE
FYI: xvfb is provided in standard linux image now

### ISSUE THREAD

**Issue by 3cp** [GabrielBB/xvfb-action#2]
Thanks for this great package. After play with it for a while, I read from the job logs that it seems xvfb is already installed in standard linux image.

So I tried following setup without using this package, and it worked.

```
- run: xvfb-run -a npm test
  if: runner.os == 'Linux'
- run: npm test
  if: runner.os != 'Linux'
```

**Comment by GabrielBB** [comment]
@3cp Wow, for real? I have to test that. That would make this package pretty much useless

**Comment by 3cp** [comment]
They probably added the xvfb package after user feedback. But it's not obvious documented anywhere. They should have a section on how to deal with various browser test.

**Comment by GabrielBB** [comment]
@3cp Yeah, they added the package. That’s great! I should add a disclaimer to this project.

Thanks for notifying

**Comment by evandrocoan** [comment]
What/where is the disclainer?

**Comment by ShaMan123** [comment]
This should be PINNED
