### ISSUE TITLE
Update tags

### ISSUE THREAD

**Issue by felipecrs** [GabrielBB/xvfb-action#20]
Hey, could you please update the `v1` tag?

```sh-session
git tag -f v1 v1.4
git push --force origin v1
```

You may also want to delete some other tags, maybe they were created mistakenly:

```sh-session
git push --delete origin v.14
git push --delete origin v.1.4
```

https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#recommendations

References https://github.com/felipecrs/vscode-gerrit/pull/3

**Comment by felipecrs** [comment]
@GabrielBB

**Comment by GabrielBB** [comment]
Thabnjs @felipecrs Updated `v1` to `v1.5`
