### ISSUE TITLE
Node.js 12 actions are deprecated.

### ISSUE THREAD

**Issue by unional** [GabrielBB/xvfb-action#30]
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: GabrielBB/xvfb-action

**Comment by tlambert03** [comment]
hey @GabrielBB ... Just checking in.  Are you still maintaining this? or should we look into a fork for node16?

**Comment by alisonatwork** [comment]
After a couple months of no feedback on this ticket, I tried to find another way to fix this, and the good news is that the `ubuntu-latest` image now includes `xvfb-run` so there is no need to overlay this image any more.

See this PR for how I fixed it for the amVim VS Code extension: https://github.com/aioutecism/amVim-for-VSCode/pull/315

**Comment by ssbarnea** [comment]
As the maintenance status of this extension is under question, you might want to switch to https://github.com/coactions/setup-xvfb which already sorted this issue.

**Comment by laeubi** [comment]
Any update on this?

**Comment by ssbarnea** [comment]
@laeubi That is why I forked it under https://github.com/coactions/setup-xvfb so we can continue maintaining it as a community. GH is full of orphan projects and most of them are under personal accounts.

**Comment by GabrielBB** [comment]
Thank you so much @ssbarnea . I updated my README to notify deprecation and link to the new repo. I'll be closing this issue as the new repo solves it already

**Comment by GabrielBB** [comment]
@ssbarnea Okay, you can invite me. Do you know why the "contributors" section is not showing there, like it's shown here:

![image](https://user-images.githubusercontent.com/8752823/226596811-c2dbb4be-7f27-49f9-9f43-d4ac6abe907e.png)
