### ISSUE TITLE
Add `working-directory` parameter for running commands in sub-directories

### ISSUE THREAD

**Issue by anweiss** [GabrielBB/xvfb-action#4]
At the moment, it's not possible to use this Action within a sub-directory. @GabrielBB per your [comment](https://github.com/juliangruber/browser-run/issues/147#issuecomment-580958935), is this something you are still willing to support? Thanks

**Comment by GabrielBB** [comment]
> At the moment, it's not possible to use this Action within a sub-directory. @GabrielBB per your [comment](https://github.com/juliangruber/browser-run/issues/147#issuecomment-580958935), is this something you are still willing to support? Thanks

@anweiss Yes, I forgot about it. I still think It should be done. I’ll see if I can do it tomorrow

**Comment by GabrielBB** [comment]
Added in https://github.com/GabrielBB/xvfb-action/pull/5 @v1.2
